### ISSUE TITLE
Broken for when second variable set  is boolean.

### ISSUE THREAD

**Issue by roycetech** [roycetech/rast#3]
Example

```yaml
---
specs:
  '#valid?':
    variables:
      Transaction Type:
        - Online
        - Retail
      Product: boolean
      Path:
        - Public
        - Private
      Promo:
        - With Valid Promo
        - With Invalid Promo
        - Without Promo
    outcomes:
      false: false[1]
```
"Expected Output" was the same for all.
